# Generated by Django 5.2 on 2025-10-26 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trackinghistory',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
