# Generated by Django 5.2 on 2025-11-09 06:39

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tracker", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="CurrentBalence",
        ),
    ]
